<<<<<<< Updated upstream
---
title: Johanna Fageras.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-slate
=======
theme: jekyll-theme-slate
title: Johannas homepage
description: Bookmark Me!
>>>>>>> Stashed changes
